services:
  bot:
    image: vek123/hello-tg-bot
    env_file:
      - .env

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MDB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MDB_PASSWORD}
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MDB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MDB_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_URL}
      ME_CONFIG_BASICAUTH: false